### ISSUE TITLE
Support systemd

### ISSUE THREAD

**Issue by dhoer** [dhoer/chef-play#3]
Check if platform has systemd, if so, use systemd.

**Comment by dhoer** [comment]
@kebeda What is the status on this?

**Comment by kebeda** [comment]
Sorry, haven't had any time to address it yet. I know we were scheduled to
talk about the repeatable scripts yesterday, but I'm fighting fires in
production and trying to get 1.12 released out the door!

**Comment by dhoer** [comment]
Version 2.0.0 has support for systemd.
