### ISSUE TITLE
Is there plans to publish this to the supermarket?

### ISSUE THREAD

**Issue by b4hand** [dhoer/chef-play#5]
There was a playframework cookbook on supermarket at one point in time, I'm not sure if that was originally https://github.com/dhoer/chef-playframework since the page is no longer available, and if so, if this repo is the successor to the old cookbook, but even if not, it might be nice to publish this to the supermarket since there's not currently a good public cookbook for the play framework. [This cookbook](https://supermarket.chef.io/cookbooks/deploy-play) appears to be defunct as the linked repo doesn't exist anymore.

**Comment by dhoer** [comment]
This is published to supermarket: https://supermarket.chef.io/cookbooks/play

**Comment by b4hand** [comment]
Thanks, somehow that got missed when I was searching.
